version: '3.8'

services:
  web:
    environment:
      - ODOO_DEBUG=true 
    depends_on:
      - db
    build: .
    ports:
      - "8069:8069"
      - "5678:5678"
    volumes:
      - odoo-web-data:/mnt/filestore
      - ./odoo.dev.cfg:/etc/odoo/odoo.conf
      - .:/mnt/extra-addons
      - ./entrypoint.sh:/entrypoint.sh
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:

